# Generated by Django 5.2.3 on 2025-06-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='credit_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='num_credit_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='yearly_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
