# Generated by Django 5.2.3 on 2025-06-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_client_credit_score_client_num_credit_cards_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='card',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='updated_at',
        ),
    ]
