# Generated by Django 5.2.3 on 2025-06-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_card_acct_open_date_card_card_on_dark_web_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expires',
            field=models.CharField(max_length=8),
        ),
    ]
