# Generated by Django 5.2.3 on 2025-06-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_card_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='errors',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mcc',
            field=models.IntegerField(default=1000),
        ),
    ]
