# Generated by Django 5.2.3 on 2025-06-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_transaction_errors_transaction_mcc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='use_chip',
            field=models.CharField(choices=[('chip', 'Chip Transaction'), ('swipe', 'Swipe Transaction')], default='Chip Transaction'),
        ),
    ]
