# Generated by Django 5.2.3 on 2025-06-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_transaction_use_chip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='errors',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
