# Generated by Django 5.2.3 on 2025-06-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_transaction_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='merchant_state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
