# Generated by Django 5.2.3 on 2025-06-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_transaction_merchant_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='merchant_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
